[project]
name = "python-gppi"
version = "0.1.0"
requires-python = ">=3.9"
dependencies = [
    "nibabel>=5.3.3",
    "nilearn>=0.12.1",
    "numpy>=2.0.2",
    "pandas>=2.3.3",
    "scikit-learn>=1.6.1",
    "scipy>=1.13.1",
]
